apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: joelinhoastron747/django_blog:latest
        command: ["celery", "-A", "blog_project", "worker", "--loglevel=info"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: blog_project.settings
        - name: DATABASE_HOST
          value: mysql
        - name: DATABASE_NAME
          value: blog_post
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          value: root
        - name: CELERY_BROKER_URL
          value: amqp://usebr:password@rabbitmq:5672//
        volumeMounts:
        - mountPath: /app/media
          name: media-pvc
      volumes:
      - name: media-pvc
        persistentVolumeClaim:
          claimName: media-pvc
